#!/bin/bash

# Kyverno CLI scanning script for local testing
# Usage: ./scripts/kyverno-scan.sh

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

KYVERNO_VERSION="v1.12.0"
REPORTS_DIR="./kyverno-reports"

echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Kyverno Policy Scanning                  ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════╝${NC}"
echo ""

# Check if Kyverno CLI is installed
if ! command -v kyverno &> /dev/null; then
    echo -e "${YELLOW}Installing Kyverno CLI ${KYVERNO_VERSION}...${NC}"
    
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m)
    
    if [ "$ARCH" = "x86_64" ]; then
        ARCH="x86_64"
    elif [ "$ARCH" = "arm64" ] || [ "$ARCH" = "aarch64" ]; then
        ARCH="arm64"
    fi
    
    wget -q "https://github.com/kyverno/kyverno/releases/download/${KYVERNO_VERSION}/kyverno-cli_${KYVERNO_VERSION}_${OS}_${ARCH}.tar.gz"
    tar -xzf "kyverno-cli_${KYVERNO_VERSION}_${OS}_${ARCH}.tar.gz"
    chmod +x kyverno
    sudo mv kyverno /usr/local/bin/ 2>/dev/null || mv kyverno /usr/local/bin/
    rm -f "kyverno-cli_${KYVERNO_VERSION}_${OS}_${ARCH}.tar.gz"
    
    echo -e "${GREEN}✅ Kyverno CLI installed${NC}"
fi

echo -e "${BLUE}Kyverno Version: $(kyverno version)${NC}"
echo ""

# Create reports directory
mkdir -p "${REPORTS_DIR}"

# Check if Helm is installed
if ! command -v helm &> /dev/null; then
    echo -e "${RED}❌ Helm not found. Please install Helm.${NC}"
    exit 1
fi

# Render Helm templates
echo -e "${YELLOW}📦 Rendering Helm templates...${NC}"
helm template simpletimeservice ./kubernetes/helm-chart \
    --namespace simpletimeservice \
    --set image.tag=latest \
    > "${REPORTS_DIR}/rendered-manifests.yaml"

echo -e "${GREEN}✅ Helm templates rendered${NC}"
echo ""

# Scan with Baseline policies
echo -e "${YELLOW}🛡️ Scanning with Baseline Pod Security Standards...${NC}"
kyverno apply kubernetes/kyverno-policies/baseline/ \
    --resource "${REPORTS_DIR}/rendered-manifests.yaml" \
    --policy-report \
    > "${REPORTS_DIR}/baseline-report.txt" 2>&1 || true

echo -e "${GREEN}✅ Baseline scan complete${NC}"
cat "${REPORTS_DIR}/baseline-report.txt"
echo ""

# Scan with Restricted policies
echo -e "${YELLOW}🛡️ Scanning with Restricted Pod Security Standards...${NC}"
kyverno apply kubernetes/kyverno-policies/restricted/ \
    --resource "${REPORTS_DIR}/rendered-manifests.yaml" \
    --policy-report \
    > "${REPORTS_DIR}/restricted-report.txt" 2>&1 || true

echo -e "${GREEN}✅ Restricted scan complete${NC}"
cat "${REPORTS_DIR}/restricted-report.txt"
echo ""

# Scan standalone manifests
echo -e "${YELLOW}🛡️ Scanning standalone Kubernetes manifests...${NC}"
kyverno apply kubernetes/kyverno-policies/ \
    --resource kubernetes/deployment.yaml \
    --policy-report \
    > "${REPORTS_DIR}/standalone-report.txt" 2>&1 || true

echo -e "${GREEN}✅ Standalone manifests scan complete${NC}"
cat "${REPORTS_DIR}/standalone-report.txt"
echo ""

# Generate summary
echo -e "${YELLOW}📄 Generating summary report...${NC}"
cat > "${REPORTS_DIR}/summary.md" <<EOF
# Kyverno Policy Scan Summary

**Date**: $(date)
**Kyverno Version**: ${KYVERNO_VERSION}

## Policies Applied

### Baseline (4 policies)
- disallow-privileged-containers
- disallow-host-namespaces
- disallow-host-path
- disallow-host-ports

### Restricted (3 policies)
- require-run-as-nonroot
- disallow-privilege-escalation
- restrict-capabilities

## Scan Results

### Helm Chart Templates
\`\`\`
$(cat "${REPORTS_DIR}/baseline-report.txt")
\`\`\`

### Restricted Policies
\`\`\`
$(cat "${REPORTS_DIR}/restricted-report.txt")
\`\`\`

### Standalone Manifests
\`\`\`
$(cat "${REPORTS_DIR}/standalone-report.txt")
\`\`\`

## Recommendations

1. Review any policy violations
2. Update manifests to comply with Pod Security Standards
3. Consider changing validationFailureAction from Audit to Enforce
4. Regularly scan manifests before deployment

---
*Generated by kyverno-scan.sh*
EOF

echo -e "${GREEN}✅ Summary report generated${NC}"
echo ""

echo -e "${BLUE}╔════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║      Kyverno Scan Complete                 ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}📁 All reports saved to: ${REPORTS_DIR}/${NC}"
echo ""
echo -e "${YELLOW}View reports:${NC}"
echo "  cat ${REPORTS_DIR}/summary.md"
echo "  cat ${REPORTS_DIR}/baseline-report.txt"
echo "  cat ${REPORTS_DIR}/restricted-report.txt"

